/* ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : LEDred.h
**     Project     : ProcessorExpert
**     Processor   : MKL25Z128VLK4
**     Component   : LED
**     Version     : Component 01.054, Driver 01.00, CPU db: 3.00.000
**     Compiler    : GNU C Compiler
**     Date/Time   : 2015-11-11, 15:28, # CodeGen: 16
**     Abstract    :
**          This component implements a universal driver for a single LED.
**     Settings    :
**          Component name                                 : LEDred
**          Turned On with initialization                  : no
**          HW Interface                                   : 
**            On/Off                                       : Enabled
**              Pin                                        : LEDpin
**            PWM                                          : Disabled
**            High Value means ON                          : no
**          Shell                                          : Disabled
**     Contents    :
**         Init       - void LEDred_Init(void);
**         Deinit     - void LEDred_Deinit(void);
**         On         - void LEDred_On(void);
**         Off        - void LEDred_Off(void);
**         Neg        - void LEDred_Neg(void);
**         Get        - byte LEDred_Get(void);
**         Put        - void LEDred_Put(byte val);
**         SetRatio16 - void LEDred_SetRatio16(word ratio);
**
**     License   :  Open Source (LGPL)
**     Copyright : (c) Copyright Erich Styger, 2012, all rights reserved.
**     Web: http://mcuoneclipse.com
**     This an open source software implementing an LED driver using Processor Expert.
**     This is a free software and is opened for education, research and commercial developments under license policy of following terms:
**     * This is a free software and there is NO WARRANTY.
**     * No restriction on use. You can use, modify and redistribute it for personal, non-profit or commercial product UNDER YOUR RESPONSIBILITY.
**     * Redistributions of source code must retain the above copyright notice.
** ###################################################################*/
/*!
** @file LEDred.h
** @version 01.00
** @brief
**          This component implements a universal driver for a single LED.
*/         
/*!
**  @addtogroup LEDred_module LEDred module documentation
**  @{
*/         

#ifndef __LEDred_H
#define __LEDred_H

/* MODULE LEDred. */

/* Include shared modules, which are used for whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
/* Include inherited beans */
#include "LEDpin2.h"

#include "Cpu.h"

#define LEDred_ClrVal()    LEDpin2_ClrVal() /* put the pin on low level */
#define LEDred_SetVal()    LEDpin2_SetVal() /* put the pin on high level */
#define LEDred_SetInput()  LEDpin2_SetInput() /* use the pin as input pin */
#define LEDred_SetOutput() LEDpin2_SetOutput() /* use the pin as output pin */

#define LEDred_PARSE_COMMAND_ENABLED  0 /* set to 1 if method ParseCommand() is present, 0 otherwise */


#define LEDred_On() LEDpin2_ClrVal()
/*
** ===================================================================
**     Method      :  LEDred_On (component LED)
**     Description :
**         This turns the LED on.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

#define LEDred_Off() LEDpin2_SetVal()
/*
** ===================================================================
**     Method      :  LEDred_Off (component LED)
**     Description :
**         This turns the LED off.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

#define LEDred_Neg() LEDpin2_NegVal()
/*
** ===================================================================
**     Method      :  LEDred_Neg (component LED)
**     Description :
**         This negates/toggles the LED
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

#define LEDred_Get() (!(LEDpin2_GetVal()))
/*
** ===================================================================
**     Method      :  LEDred_Get (component LED)
**     Description :
**         This returns logical 1 in case the LED is on, 0 otherwise.
**     Parameters  : None
**     Returns     :
**         ---             - Status of the LED (on or off)
** ===================================================================
*/

#define LEDred_Init() LEDred_Off()
/*
** ===================================================================
**     Method      :  LEDred_Init (component LED)
**     Description :
**         Performs the LED driver initialization.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

#define LEDred_Put(val)  ((val) ? LEDred_On() : LEDred_Off())
/*
** ===================================================================
**     Method      :  LEDred_Put (component LED)
**     Description :
**         Turns the LED on or off.
**     Parameters  :
**         NAME            - DESCRIPTION
**         val             - value to define if the LED has to be on or
**                           off.
**     Returns     : Nothing
** ===================================================================
*/

void LEDred_Deinit(void);
/*
** ===================================================================
**     Method      :  LEDred_Deinit (component LED)
**     Description :
**         Deinitializes the driver
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

void LEDred_SetRatio16(word ratio);
/*
** ===================================================================
**     Method      :  LEDred_SetRatio16 (component LED)
**     Description :
**         Method to specify the duty cycle. If using a PWM pin, this
**         means the duty cycle is set. For On/off pins, values smaller
**         0x7FFF means off, while values greater means on.
**     Parameters  :
**         NAME            - DESCRIPTION
**         ratio           - Ratio value, where 0 means 'off' and
**                           0xffff means 'on'
**     Returns     : Nothing
** ===================================================================
*/

/* END LEDred. */

#endif
/* ifndef __LEDred_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.09]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
